package com.example.dllo.zhangxiwei_travelapp.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.zhangxiwei_travelapp.entity.CollectEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COLLECT_ENTITY".
*/
public class CollectEntityDao extends AbstractDao<CollectEntity, Long> {

    public static final String TABLENAME = "COLLECT_ENTITY";

    /**
     * Properties of entity CollectEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CollectType = new Property(1, String.class, "collectType", false, "COLLECT_TYPE");
        public final static Property CollectTitle = new Property(2, String.class, "collectTitle", false, "COLLECT_TITLE");
        public final static Property CollectImageUrl = new Property(3, String.class, "collectImageUrl", false, "COLLECT_IMAGE_URL");
    };


    public CollectEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CollectEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COLLECT_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COLLECT_TYPE\" TEXT," + // 1: collectType
                "\"COLLECT_TITLE\" TEXT," + // 2: collectTitle
                "\"COLLECT_IMAGE_URL\" TEXT);"); // 3: collectImageUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COLLECT_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CollectEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String collectType = entity.getCollectType();
        if (collectType != null) {
            stmt.bindString(2, collectType);
        }
 
        String collectTitle = entity.getCollectTitle();
        if (collectTitle != null) {
            stmt.bindString(3, collectTitle);
        }
 
        String collectImageUrl = entity.getCollectImageUrl();
        if (collectImageUrl != null) {
            stmt.bindString(4, collectImageUrl);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CollectEntity readEntity(Cursor cursor, int offset) {
        CollectEntity entity = new CollectEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // collectType
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // collectTitle
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // collectImageUrl
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CollectEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCollectType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCollectTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCollectImageUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CollectEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CollectEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
