package com.example.dllo.zhangxiwei_travelapp.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLLECT_ENTITY".
 */
public class CollectEntity {

    private Long id;
    private String collectType;
    private String collectTitle;
    private String collectImageUrl;

    public CollectEntity() {
    }

    public CollectEntity(Long id) {
        this.id = id;
    }

    public CollectEntity(Long id, String collectType, String collectTitle, String collectImageUrl) {
        this.id = id;
        this.collectType = collectType;
        this.collectTitle = collectTitle;
        this.collectImageUrl = collectImageUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCollectType() {
        return collectType;
    }

    public void setCollectType(String collectType) {
        this.collectType = collectType;
    }

    public String getCollectTitle() {
        return collectTitle;
    }

    public void setCollectTitle(String collectTitle) {
        this.collectTitle = collectTitle;
    }

    public String getCollectImageUrl() {
        return collectImageUrl;
    }

    public void setCollectImageUrl(String collectImageUrl) {
        this.collectImageUrl = collectImageUrl;
    }

}
