package com.example.dllo.zhangxiwei_travelapp.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.zhangxiwei_travelapp.entity.RecentStrategyEntity;

import com.example.dllo.zhangxiwei_travelapp.entity.RecentStrategyEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 * GreenDao创建的类
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentStrategyEntityDaoConfig;

    private final RecentStrategyEntityDao recentStrategyEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentStrategyEntityDaoConfig = daoConfigMap.get(RecentStrategyEntityDao.class).clone();
        recentStrategyEntityDaoConfig.initIdentityScope(type);

        recentStrategyEntityDao = new RecentStrategyEntityDao(recentStrategyEntityDaoConfig, this);

        registerDao(RecentStrategyEntity.class, recentStrategyEntityDao);
    }
    
    public void clear() {
        recentStrategyEntityDaoConfig.getIdentityScope().clear();
    }

    public RecentStrategyEntityDao getRecentStrategyEntityDao() {
        return recentStrategyEntityDao;
    }

}
