package com.example.dllo.zhangxiwei_travelapp.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.zhangxiwei_travelapp.entity.RecentStrategyEntity;
import com.example.dllo.zhangxiwei_travelapp.entity.UserEntity;
import com.example.dllo.zhangxiwei_travelapp.entity.CollectEntity;

import com.example.dllo.zhangxiwei_travelapp.entity.RecentStrategyEntityDao;
import com.example.dllo.zhangxiwei_travelapp.entity.UserEntityDao;
import com.example.dllo.zhangxiwei_travelapp.entity.CollectEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recentStrategyEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig collectEntityDaoConfig;

    private final RecentStrategyEntityDao recentStrategyEntityDao;
    private final UserEntityDao userEntityDao;
    private final CollectEntityDao collectEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recentStrategyEntityDaoConfig = daoConfigMap.get(RecentStrategyEntityDao.class).clone();
        recentStrategyEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        collectEntityDaoConfig = daoConfigMap.get(CollectEntityDao.class).clone();
        collectEntityDaoConfig.initIdentityScope(type);

        recentStrategyEntityDao = new RecentStrategyEntityDao(recentStrategyEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        collectEntityDao = new CollectEntityDao(collectEntityDaoConfig, this);

        registerDao(RecentStrategyEntity.class, recentStrategyEntityDao);
        registerDao(UserEntity.class, userEntityDao);
        registerDao(CollectEntity.class, collectEntityDao);
    }
    
    public void clear() {
        recentStrategyEntityDaoConfig.getIdentityScope().clear();
        userEntityDaoConfig.getIdentityScope().clear();
        collectEntityDaoConfig.getIdentityScope().clear();
    }

    public RecentStrategyEntityDao getRecentStrategyEntityDao() {
        return recentStrategyEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public CollectEntityDao getCollectEntityDao() {
        return collectEntityDao;
    }

}
