package com.example.dllo.zhangxiwei_travelapp.entity;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dllo.zhangxiwei_travelapp.entity.RecentStrategyEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECENT_STRATEGY_ENTITY".
 * GreenDao创建的类
*/
public class RecentStrategyEntityDao extends AbstractDao<RecentStrategyEntity, Long> {

    public static final String TABLENAME = "RECENT_STRATEGY_ENTITY";

    /**
     * Properties of entity RecentStrategyEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PlaceName = new Property(1, String.class, "placeName", false, "PLACE_NAME");
        public final static Property PlaceNum = new Property(2, Integer.class, "placeNum", false, "PLACE_NUM");
    };


    public RecentStrategyEntityDao(DaoConfig config) {
        super(config);
    }
    
    public RecentStrategyEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECENT_STRATEGY_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PLACE_NAME\" TEXT," + // 1: placeName
                "\"PLACE_NUM\" INTEGER);"); // 2: placeNum
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECENT_STRATEGY_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecentStrategyEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String placeName = entity.getPlaceName();
        if (placeName != null) {
            stmt.bindString(2, placeName);
        }
 
        Integer placeNum = entity.getPlaceNum();
        if (placeNum != null) {
            stmt.bindLong(3, placeNum);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RecentStrategyEntity readEntity(Cursor cursor, int offset) {
        RecentStrategyEntity entity = new RecentStrategyEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // placeName
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // placeNum
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecentStrategyEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlaceName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPlaceNum(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RecentStrategyEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RecentStrategyEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
