package com.example.dllo.zhangxiwei_travelapp.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECENT_STRATEGY_ENTITY".
 */
public class RecentStrategyEntity {

    private Long id;
    private String placeName;
    private Integer placeNum;

    public RecentStrategyEntity() {
    }

    public RecentStrategyEntity(Long id) {
        this.id = id;
    }

    public RecentStrategyEntity(Long id, String placeName, Integer placeNum) {
        this.id = id;
        this.placeName = placeName;
        this.placeNum = placeNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPlaceName() {
        return placeName;
    }

    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }

    public Integer getPlaceNum() {
        return placeNum;
    }

    public void setPlaceNum(Integer placeNum) {
        this.placeNum = placeNum;
    }

}
